{
 "title": "Budgetbook_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{pod=\"expense-9ff86b999-h9xkh\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bb_expenses_get_all_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New User Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bb_auth_new_user_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Existing User Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bb_auth_existing_user_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Statistics Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bb_aufrufe_statistics_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PUT Expenses",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "expenses_count", "legendFormat": "__auto" }
   ]
  }
 ]
}