apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: expense
  name: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense
  template:
    metadata:
      labels:
        app: expense
    spec:
      containers:
        - image: expense:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: DB_HOST
              value: "mysql.default.svc.cluster.local"
            - name: DB_USER
              value: "budgetbook"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql-password
            - name: DB_NAME
              value: "budgetbook"
            - name: DB_PORT
              value: "3306"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: budgetbook
                  key: JWT_SECRET
          name: expense
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
