# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  tls:
    - hosts:
        - budgetbook.me
      secretName: budgetbook.me
  ingressClassName: nginx
  rules:
    - host: budgetbook.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 3000
          - path: /api/expense
            pathType: Prefix
            backend:
              service:
                name: expense
                port:
                  number: 3000
          - path: /api/statistics
            pathType: Prefix
            backend:
              service:
                name: statistics
                port:
                  number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grafana
  namespace: metrics
spec:
  tls:
    - hosts:
        - grafana.budgetbook.me
      secretName: wildcard.budgetbook.me
  ingressClassName: nginx
  rules:
    - host: grafana.budgetbook.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-prometheus-grafana
                port:
                  number: 80