apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: statistics
  name: statistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics
  template:
    metadata:
      labels:
        app: statistics
    spec:
      containers:
        - image: statistics:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: DB_HOST
              value: "mysql.default.svc.cluster.local"
            - name: DB_USER
              value: "budgetbook"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql-password
            - name: DB_NAME
              value: "budgetbook"
            - name: DB_PORT
              value: "3306"
            - name: JWT_SECRET
              value: "It3n4FJ2uO8VJhMXLQobzIyqKvWMnI"
          name: statistics
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
