apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: statistics
  name: statistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics
  template:
    metadata:
      labels:
        app: statistics
    spec:
      containers:
        - image: statistics:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: DB_HOST
              value: "mysql.default.svc.cluster.local"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "Xt7g21lbHX"
            - name: DB_NAME
              value: "budgetbook"
            - name: DB_PORT
              value: "3306"
            - name: GOOGLE_CLIENT_ID
              value: "603681528642-05fq8afr2fglbdabm8532jjg1qbf91ra.apps.googleusercontent.com"
            - name: GOOGLE_CLIENT_SECRET
              value: "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"
            - name: GOOGLE_CALLBACK_URL
              value: "http://budgetbook.me/api/auth/google/redirect"
            - name: REDIRECT_HOST
              value: "http://budgetbook.me"
          name: statistics
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
