auth:
  image: auth:latest
  imagePullPolicy: Never
  replicas: 1
  port: 3000
  targetPort: 3000
  restartPolicy: Always
  env:
    - name: DB_HOST
      value: ImxvY2FsaG9zdCI=
    - name: DB_NAME
      value: ImJ1ZGdldGJvb2si
    - name: DB_PASSWORD
      value: ImFkbWluIg==
    - name: DB_PORT
      value: IjMzMDYi
    - name: DB_USER
      value: InJvb3Qi
    - name: GOOGLE_CALLBACK_URL
      value: aHR0cHM6Ly9idWRnZXRib29rLm1lL2FwaS9hdXRoL2dvb2dsZS9yZWRpcmVjdAo=
    - name: GOOGLE_CLIENT_ID
      value: NjAzNjgxNTI4NjQyLTA1ZnE4YWZyMmZnbGJkYWJtODUzMmpqZzFxYmY5MXJhLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tCg==
    - name: GOOGLE_CLIENT_SECRET
      value: R09DU1BYLWFUNG9Od1FmMXRLaUlxM1NKUC1YQUV3S1hTeGEK
    - name: JWT_SECRET
      value: ODI5YzRkYjdlNDYxNTM2NGIwZDMxNDIyYzVhYjUzNmVjNWQzNTQyY2ViMjZhMjVmMmI2OGRhNTI3Y2ZhOGJhMgo=
expense:
  image: expense:latest
  restartPolicy: Always
  port: 3000
  targetPort: 3000
  imagePullPolicy: Never
  replicas: 1
  env:
    - name: DB_HOST
      value: ImxvY2FsaG9zdCI=
    - name: DB_NAME
      value: ImJ1ZGdldGJvb2si
    - name: DB_PASSWORD
      value: ImFkbWluIg==
    - name: DB_PORT
      value: IjMzMDYi
    - name: DB_USER
      value: InJvb3Qi
    - name: GOOGLE_CALLBACK_URL
      value: aHR0cHM6Ly9idWRnZXRib29rLm1lL2FwaS9hdXRoL2dvb2dsZS9yZWRpcmVjdAo=
    - name: GOOGLE_CLIENT_ID
      value: NjAzNjgxNTI4NjQyLTA1ZnE4YWZyMmZnbGJkYWJtODUzMmpqZzFxYmY5MXJhLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tCg==
    - name: GOOGLE_CLIENT_SECRET
      value: R09DU1BYLWFUNG9Od1FmMXRLaUlxM1NKUC1YQUV3S1hTeGEK
    - name: JWT_SECRET
      value: ODI5YzRkYjdlNDYxNTM2NGIwZDMxNDIyYzVhYjUzNmVjNWQzNTQyY2ViMjZhMjVmMmI2OGRhNTI3Y2ZhOGJhMgo=
statistics:
  image: statistics:latest
  restartPolicy: Always
  port: 3000
  targetPort: 3000
  imagePullPolicy: Never
  replicas: 1
  env:
    - name: DB_HOST
      value: ImxvY2FsaG9zdCI=
    - name: DB_NAME
      value: ImJ1ZGdldGJvb2si
    - name: DB_PASSWORD
      value: ImFkbWluIg==
    - name: DB_PORT
      value: IjMzMDYi
    - name: DB_USER
      value: InJvb3Qi
    - name: GOOGLE_CALLBACK_URL
      value: aHR0cHM6Ly9idWRnZXRib29rLm1lL2FwaS9hdXRoL2dvb2dsZS9yZWRpcmVjdAo=
    - name: GOOGLE_CLIENT_ID
      value: NjAzNjgxNTI4NjQyLTA1ZnE4YWZyMmZnbGJkYWJtODUzMmpqZzFxYmY5MXJhLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tCg==
    - name: GOOGLE_CLIENT_SECRET
      value: R09DU1BYLWFUNG9Od1FmMXRLaUlxM1NKUC1YQUV3S1hTeGEK
    - name: JWT_SECRET
      value: ODI5YzRkYjdlNDYxNTM2NGIwZDMxNDIyYzVhYjUzNmVjNWQzNTQyY2ViMjZhMjVmMmI2OGRhNTI3Y2ZhOGJhMgo=
frontend:
  image: frontend:latest
  restartPolicy: Always
  port: 80
  targetPort: 80
  imagePullPolicy: Never
  replicas: 1
