apiVersion: v1
kind: Service
metadata:
  name: frontend  
spec:
  selector: 
    app: frontend
  ports:
    - name: "8080"
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.targetPort }}
