on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build and push image tags
      uses: docker/build-push-action@v5
      with:
        context: frondend
        file: Dockerfile
        push: true
        tags: |
          ${{ github.repository }}:${{ github.ref_name.replace('refs/tags/', '') }}

