name: Docker Image CI

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Extract metadata (tags) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        tags: |
          type=semver,pattern={{version}}

    - name: Bump Version
      id: bump
      uses: docker/bump-action@v1
      with:
        tag: ${{ steps.meta.outputs.tags }}

    - name: Build and push Docker image frontend
      uses: docker/build-push-action@v2
      with:
        context: frontend
        file: Dockerfile
        push: true
        tags: aws2307/budgetbook-frontend:${{ steps.bump.outputs.new_tag }}

    - name: Build and push Docker image auth
      uses: docker/build-push-action@v2
      with:
        context: auth
        file: Dockerfile
        push: true
        tags: aws2307/budgetbook-auth:${{ steps.bump.outputs.new_tag }}

    - name: Build and push Docker image expense
      uses: docker/build-push-action@v2
      with:
        context: expense
        file: Dockerfile
        push: true
        tags: aws2307/budgetbook-expense:${{ steps.bump.outputs.new_tag }}

    - name: Build and push Docker image statistics
      uses: docker/build-push-action@v2
      with:
        context: statistics
        file: Dockerfile
        push: true
        tags: aws2307/budgetbook-statistics:${{ steps.bump.outputs.new_tag }}
