name: Docker Image CI

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Extract metadata (tags) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        tags: ${{ github.ref }}

    - name: Build and push Docker images
      run: |
        for service in frontend auth expense statistics; do
          docker build . --file $service/Dockerfile --tag aws2307/budgetbook-$service:${{ steps.meta.outputs.tags }}
          docker push aws2307/budgetbook-$service:${{ steps.meta.outputs.tags }}
        done
