name: 'Expense'

on:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'expense/**'
  workflow_dispatch:
  pull_request:
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./expense

    steps:
      - name: checkout
        uses: actions/checkout@v4
           
      - name: ci
        run:  npm ci
      - name: lint 
        run: npm run lint
      # - name: test
      #   run: npm run test
      - name: build
        run: npm run build