name: 'Statistics'

on:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'statistics/**'
  workflow_dispatch:
  pull_request:
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./statistics

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: feature/github_workflow
           
      - name: ci
        run:  npm ci
      - name: lint 
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build